//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Aliens_Group\Sparky_Studios\spsl\SPSL.Language\SPSL.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace SPSL.Language {

using SPSL.Language.AST;


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISPSLListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class SPSLBaseListener : ISPSLListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile([NotNull] SPSLParser.FileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile([NotNull] SPSLParser.FileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.namespaceDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespaceDefinition([NotNull] SPSLParser.NamespaceDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.namespaceDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespaceDefinition([NotNull] SPSLParser.NamespaceDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.namespacedTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespacedTypeName([NotNull] SPSLParser.NamespacedTypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.namespacedTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespacedTypeName([NotNull] SPSLParser.NamespacedTypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.fileLevelDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFileLevelDefinition([NotNull] SPSLParser.FileLevelDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.fileLevelDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFileLevelDefinition([NotNull] SPSLParser.FileLevelDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Struct</c>
	/// labeled alternative in <see cref="SPSLParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct([NotNull] SPSLParser.StructContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Struct</c>
	/// labeled alternative in <see cref="SPSLParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct([NotNull] SPSLParser.StructContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Enum</c>
	/// labeled alternative in <see cref="SPSLParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnum([NotNull] SPSLParser.EnumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Enum</c>
	/// labeled alternative in <see cref="SPSLParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnum([NotNull] SPSLParser.EnumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.structDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDefinition([NotNull] SPSLParser.StructDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.structDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDefinition([NotNull] SPSLParser.StructDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.enumDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDefinition([NotNull] SPSLParser.EnumDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.enumDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDefinition([NotNull] SPSLParser.EnumDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.interface"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterface([NotNull] SPSLParser.InterfaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.interface"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterface([NotNull] SPSLParser.InterfaceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.interfaceDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceDefinition([NotNull] SPSLParser.InterfaceDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.interfaceDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceDefinition([NotNull] SPSLParser.InterfaceDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.interfacesList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfacesList([NotNull] SPSLParser.InterfacesListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.interfacesList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfacesList([NotNull] SPSLParser.InterfacesListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.shaderFragment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShaderFragment([NotNull] SPSLParser.ShaderFragmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.shaderFragment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShaderFragment([NotNull] SPSLParser.ShaderFragmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.shaderFragmentDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShaderFragmentDefinition([NotNull] SPSLParser.ShaderFragmentDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.shaderFragmentDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShaderFragmentDefinition([NotNull] SPSLParser.ShaderFragmentDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.shader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShader([NotNull] SPSLParser.ShaderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.shader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShader([NotNull] SPSLParser.ShaderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.shaderDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShaderDefinition([NotNull] SPSLParser.ShaderDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.shaderDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShaderDefinition([NotNull] SPSLParser.ShaderDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.useDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUseDirective([NotNull] SPSLParser.UseDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.useDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUseDirective([NotNull] SPSLParser.UseDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.shaderMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShaderMember([NotNull] SPSLParser.ShaderMemberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.shaderMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShaderMember([NotNull] SPSLParser.ShaderMemberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotation([NotNull] SPSLParser.AnnotationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotation([NotNull] SPSLParser.AnnotationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirective([NotNull] SPSLParser.DirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirective([NotNull] SPSLParser.DirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.precisionDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrecisionDirective([NotNull] SPSLParser.PrecisionDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.precisionDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrecisionDirective([NotNull] SPSLParser.PrecisionDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.shaderLangDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShaderLangDirective([NotNull] SPSLParser.ShaderLangDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.shaderLangDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShaderLangDirective([NotNull] SPSLParser.ShaderLangDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.parameterDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterDirective([NotNull] SPSLParser.ParameterDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.parameterDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterDirective([NotNull] SPSLParser.ParameterDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.inputVarDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInputVarDefinition([NotNull] SPSLParser.InputVarDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.inputVarDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInputVarDefinition([NotNull] SPSLParser.InputVarDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.localVarDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocalVarDeclaration([NotNull] SPSLParser.LocalVarDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.localVarDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocalVarDeclaration([NotNull] SPSLParser.LocalVarDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.globalVarDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalVarDeclaration([NotNull] SPSLParser.GlobalVarDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.globalVarDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalVarDeclaration([NotNull] SPSLParser.GlobalVarDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.outputVarDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutputVarDeclaration([NotNull] SPSLParser.OutputVarDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.outputVarDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutputVarDeclaration([NotNull] SPSLParser.OutputVarDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.blockDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockDefinition([NotNull] SPSLParser.BlockDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.blockDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockDefinition([NotNull] SPSLParser.BlockDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.blockComponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockComponent([NotNull] SPSLParser.BlockComponentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.blockComponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockComponent([NotNull] SPSLParser.BlockComponentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.enumBlockComponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumBlockComponent([NotNull] SPSLParser.EnumBlockComponentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.enumBlockComponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumBlockComponent([NotNull] SPSLParser.EnumBlockComponentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypedVariableDeclaration</c>
	/// labeled alternative in <see cref="SPSLParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypedVariableDeclaration([NotNull] SPSLParser.TypedVariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypedVariableDeclaration</c>
	/// labeled alternative in <see cref="SPSLParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypedVariableDeclaration([NotNull] SPSLParser.TypedVariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UntypedVariableDeclaration</c>
	/// labeled alternative in <see cref="SPSLParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUntypedVariableDeclaration([NotNull] SPSLParser.UntypedVariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UntypedVariableDeclaration</c>
	/// labeled alternative in <see cref="SPSLParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUntypedVariableDeclaration([NotNull] SPSLParser.UntypedVariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.variableDeclarationAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarationAssignment([NotNull] SPSLParser.VariableDeclarationAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.variableDeclarationAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarationAssignment([NotNull] SPSLParser.VariableDeclarationAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.variableIdentity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableIdentity([NotNull] SPSLParser.VariableIdentityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.variableIdentity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableIdentity([NotNull] SPSLParser.VariableIdentityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.shaderFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShaderFunction([NotNull] SPSLParser.ShaderFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.shaderFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShaderFunction([NotNull] SPSLParser.ShaderFunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] SPSLParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] SPSLParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.functionHead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionHead([NotNull] SPSLParser.FunctionHeadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.functionHead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionHead([NotNull] SPSLParser.FunctionHeadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.functionSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionSignature([NotNull] SPSLParser.FunctionSignatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.functionSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionSignature([NotNull] SPSLParser.FunctionSignatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.argList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgList([NotNull] SPSLParser.ArgListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.argList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgList([NotNull] SPSLParser.ArgListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.argDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgDef([NotNull] SPSLParser.ArgDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.argDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgDef([NotNull] SPSLParser.ArgDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.functionBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionBody([NotNull] SPSLParser.FunctionBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.functionBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionBody([NotNull] SPSLParser.FunctionBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.statementBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatementBlock([NotNull] SPSLParser.StatementBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.statementBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatementBlock([NotNull] SPSLParser.StatementBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.propertyMemberReferenceExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyMemberReferenceExpression([NotNull] SPSLParser.PropertyMemberReferenceExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.propertyMemberReferenceExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyMemberReferenceExpression([NotNull] SPSLParser.PropertyMemberReferenceExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.methodMemberReferenceExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodMemberReferenceExpression([NotNull] SPSLParser.MethodMemberReferenceExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.methodMemberReferenceExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodMemberReferenceExpression([NotNull] SPSLParser.MethodMemberReferenceExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.memberReferenceExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberReferenceExpression([NotNull] SPSLParser.MemberReferenceExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.memberReferenceExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberReferenceExpression([NotNull] SPSLParser.MemberReferenceExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.invocationExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInvocationExpression([NotNull] SPSLParser.InvocationExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.invocationExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInvocationExpression([NotNull] SPSLParser.InvocationExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] SPSLParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] SPSLParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.elifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElifStatement([NotNull] SPSLParser.ElifStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.elifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElifStatement([NotNull] SPSLParser.ElifStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseStatement([NotNull] SPSLParser.ElseStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseStatement([NotNull] SPSLParser.ElseStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.switchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchStatement([NotNull] SPSLParser.SwitchStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.switchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchStatement([NotNull] SPSLParser.SwitchStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.caseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseStatement([NotNull] SPSLParser.CaseStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.caseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseStatement([NotNull] SPSLParser.CaseStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.parenthesizedExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenthesizedExpression([NotNull] SPSLParser.ParenthesizedExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.parenthesizedExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenthesizedExpression([NotNull] SPSLParser.ParenthesizedExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.newInstanceExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNewInstanceExpression([NotNull] SPSLParser.NewInstanceExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.newInstanceExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNewInstanceExpression([NotNull] SPSLParser.NewInstanceExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.parametersList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParametersList([NotNull] SPSLParser.ParametersListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.parametersList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParametersList([NotNull] SPSLParser.ParametersListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.basicExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBasicExpression([NotNull] SPSLParser.BasicExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.basicExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBasicExpression([NotNull] SPSLParser.BasicExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PostfixUnaryOperationExpression</c>
	/// labeled alternative in <see cref="SPSLParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfixUnaryOperationExpression([NotNull] SPSLParser.PostfixUnaryOperationExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PostfixUnaryOperationExpression</c>
	/// labeled alternative in <see cref="SPSLParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfixUnaryOperationExpression([NotNull] SPSLParser.PostfixUnaryOperationExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AssignmentExpression</c>
	/// labeled alternative in <see cref="SPSLParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentExpression([NotNull] SPSLParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AssignmentExpression</c>
	/// labeled alternative in <see cref="SPSLParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentExpression([NotNull] SPSLParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TernaryOperationExpression</c>
	/// labeled alternative in <see cref="SPSLParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTernaryOperationExpression([NotNull] SPSLParser.TernaryOperationExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TernaryOperationExpression</c>
	/// labeled alternative in <see cref="SPSLParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTernaryOperationExpression([NotNull] SPSLParser.TernaryOperationExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Expression</c>
	/// labeled alternative in <see cref="SPSLParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] SPSLParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Expression</c>
	/// labeled alternative in <see cref="SPSLParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] SPSLParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BinaryOperationExpression</c>
	/// labeled alternative in <see cref="SPSLParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryOperationExpression([NotNull] SPSLParser.BinaryOperationExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BinaryOperationExpression</c>
	/// labeled alternative in <see cref="SPSLParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryOperationExpression([NotNull] SPSLParser.BinaryOperationExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PrefixUnaryOperationExpression</c>
	/// labeled alternative in <see cref="SPSLParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefixUnaryOperationExpression([NotNull] SPSLParser.PrefixUnaryOperationExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PrefixUnaryOperationExpression</c>
	/// labeled alternative in <see cref="SPSLParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefixUnaryOperationExpression([NotNull] SPSLParser.PrefixUnaryOperationExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NegateOperationExpression</c>
	/// labeled alternative in <see cref="SPSLParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegateOperationExpression([NotNull] SPSLParser.NegateOperationExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NegateOperationExpression</c>
	/// labeled alternative in <see cref="SPSLParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegateOperationExpression([NotNull] SPSLParser.NegateOperationExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>CastExpression</c>
	/// labeled alternative in <see cref="SPSLParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCastExpression([NotNull] SPSLParser.CastExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CastExpression</c>
	/// labeled alternative in <see cref="SPSLParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCastExpression([NotNull] SPSLParser.CastExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.arrayAccessExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAccessExpression([NotNull] SPSLParser.ArrayAccessExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.arrayAccessExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAccessExpression([NotNull] SPSLParser.ArrayAccessExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.assignableExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignableExpression([NotNull] SPSLParser.AssignableExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.assignableExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignableExpression([NotNull] SPSLParser.AssignableExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] SPSLParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] SPSLParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakStatement([NotNull] SPSLParser.BreakStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakStatement([NotNull] SPSLParser.BreakStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.continueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueStatement([NotNull] SPSLParser.ContinueStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.continueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueStatement([NotNull] SPSLParser.ContinueStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.discardStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDiscardStatement([NotNull] SPSLParser.DiscardStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.discardStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDiscardStatement([NotNull] SPSLParser.DiscardStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.leaveControlFlowStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeaveControlFlowStatement([NotNull] SPSLParser.LeaveControlFlowStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.leaveControlFlowStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeaveControlFlowStatement([NotNull] SPSLParser.LeaveControlFlowStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.stayControlFlowStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStayControlFlowStatement([NotNull] SPSLParser.StayControlFlowStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.stayControlFlowStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStayControlFlowStatement([NotNull] SPSLParser.StayControlFlowStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] SPSLParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] SPSLParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.primitiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveExpression([NotNull] SPSLParser.PrimitiveExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.primitiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveExpression([NotNull] SPSLParser.PrimitiveExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PrimitiveConstantExpression</c>
	/// labeled alternative in <see cref="SPSLParser.constantExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveConstantExpression([NotNull] SPSLParser.PrimitiveConstantExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PrimitiveConstantExpression</c>
	/// labeled alternative in <see cref="SPSLParser.constantExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveConstantExpression([NotNull] SPSLParser.PrimitiveConstantExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UserDefinedConstantExpression</c>
	/// labeled alternative in <see cref="SPSLParser.constantExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUserDefinedConstantExpression([NotNull] SPSLParser.UserDefinedConstantExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UserDefinedConstantExpression</c>
	/// labeled alternative in <see cref="SPSLParser.constantExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUserDefinedConstantExpression([NotNull] SPSLParser.UserDefinedConstantExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.dataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDataType([NotNull] SPSLParser.DataTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.dataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDataType([NotNull] SPSLParser.DataTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.userDefinedDataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUserDefinedDataType([NotNull] SPSLParser.UserDefinedDataTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.userDefinedDataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUserDefinedDataType([NotNull] SPSLParser.UserDefinedDataTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.primitiveDataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveDataType([NotNull] SPSLParser.PrimitiveDataTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.primitiveDataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveDataType([NotNull] SPSLParser.PrimitiveDataTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPSLParser.builtinDataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBuiltinDataType([NotNull] SPSLParser.BuiltinDataTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPSLParser.builtinDataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBuiltinDataType([NotNull] SPSLParser.BuiltinDataTypeContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace SPSL.Language
